name: PR Validation, Deployment & Auto-Rollback for Salesforce

on:
  push:
    branches:
      - uat

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          version: latest

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > sfdx-auth-url.txt
          sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt -a qa-org -d

      - name: Generate Delta & Rollback Packages
        run: |
          echo y | sf plugins install sfdx-git-delta
          # Generate deploy package (changes)
          sf sgd:source:delta --to "HEAD" --from "HEAD~1" --output "delta" --ignore .github/workflows/ignore.txt
          # Generate rollback package (reverse changes)
          sf sgd:source:delta --to "HEAD~1" --from "HEAD" --output "rollback" --ignore .github/workflows/ignore.txt
          echo "Rollback package generated ✅"

      - name: Upload rollback artifact
        uses: actions/upload-artifact@v3
        with:
          name: rollback-package
          path: rollback/

      - name: Validate Metadata (check-only)
        run: |
          sfdx force:source:deploy \
            --checkonly \
            --manifest delta/package/package.xml \
            --targetusername qa-org \
            --testlevel RunLocalTests

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          version: latest

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > sfdx-auth-url.txt
          sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt -a qa-org -d

      - name: Deploy Metadata to QA
        run: |
          sfdx force:source:deploy \
            --manifest delta/package/package.xml \
            --targetusername qa-org \
            --testlevel RunLocalTests

  rollback:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()   # 🚨 Auto-run only if deploy fails
    steps:
      - name: Download rollback artifact
        uses: actions/download-artifact@v3
        with:
          name: rollback-package
          path: rollback/

      - name: Set up Salesforce CLI
        uses: sfdx-actions/setup-sfdx@v1
        with:
          version: latest

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > sfdx-auth-url.txt
          sfdx auth:sfdxurl:store --sfdx-url-file sfdx-auth-url.txt -a qa-org -d

      - name: Rollback Deployment
        run: |
          echo "🚨 Deployment failed — running rollback..."
          sfdx force:source:deploy \
            --manifest rollback/package/package.xml \
            --targetusername qa-org \
            --testlevel RunLocalTests
          echo "✅ Rollback completed"
