name: PR Validation & Deployment for Salesforce

on:
  push:
    branches:
      - uat

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js 20
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
            node-version: '20'

        - name: Force Salesforce CLI to use system Node
        run: echo "SF_USE_SYSTEM_NODE=true" >> $GITHUB_ENV

        - name: Install Salesforce CLI
          run: |
            npm install -g sfdx-cli

        - name: Install sfdx-git-delta
          run: echo y | sf plugins install sfdx-git-delta


      # Generate Delta Package
      - name: Generate Delta Package
        run: |
          SF_USE_SYSTEM_NODE=true sf sgd:source:delta --to "HEAD" --from "HEAD~1" --output "delta" --ignore .github/workflows/ignore.txt
          echo "Delta package generated ✅"

      # Validate Metadata (check-only)
      - name: Validate Metadata
        run: |
          SF_USE_SYSTEM_NODE=true sfdx force:source:deploy \
            --checkonly \
            --manifest delta/package/package.xml \
            --targetusername qa-org \
            --testlevel RunLocalTests

      # Deploy Metadata to QA
      - name: Deploy Metadata to QA
        run: |
          SF_USE_SYSTEM_NODE=true sfdx force:source:deploy \
            --manifest delta/package/package.xml \
            --targetusername qa-org \
            --testlevel RunLocalTests
